services:
  db:
    image: postgres:15
    container_name: vetcare_db
    environment:
      POSTGRES_DB: vetcare
      POSTGRES_USER: vetcare_user
      POSTGRES_PASSWORD: vetcare_pass
    ports:
      - "5432:5432"
    volumes:
      - vetcare_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/data

  api:
    build: ./api
    container_name: vetcare_api
    depends_on:
      - db
    environment:
      PORT: 3000
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: vetcare
      PGUSER: vetcare_user
      PGPASSWORD: vetcare_pass
    ports:
      - "3000:3000"

volumes:
  vetcare_data:
