services:
  db:
    image: postgres:15
    container_name: vetcare_db
    environment:
      POSTGRES_DB: vetcare
      POSTGRES_USER: vetcare_user
      POSTGRES_PASSWORD: vetcare_pass
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data/catalogos:/data/catalogos
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: vetcare_api
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: vetcare_user
      PGPASSWORD: vetcare_pass
      PGDATABASE: vetcare
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
